---
title: "Research"
---
## STUDENTS
### Masters
1. Cesilia Mambile, "*A Web Based Forum for Reliable Market Linkage between Poultry Farmers and Potential Buyers in Tanzania*"
2. Geofrey Rweikiza, "*Reducing Fragmentation in sharing of Information in E-medical Recording Systems: Case of Open MRS and Care2X*"

### PhD
1. Mathias Ombeni, "*A Framework for Monitoring Quality of Fertilizer in Supply Chain in Tanzania*"
2. Neema Mduma, "*Data-driven Approach for Predicting Student Dropout in Secondary Schools*"
3. Sarah Nyanjara, "*Integrated Quality Measurement Framework for Maternal, Neonatal and Child Health Services in Tanzania*"

### Masters Alumni

1. Gloriana Monko, **Development of an E-Cultural Heritage Portal for Improving Acquisition and Accessibility of Cultural Heritage Infromation: A Case study of Tanzania**, 2017.
2. Khalfan Ramadhani, **An Early Warning System for Enhancing Management of 
Banana Fungal Diseases: Case of Arumeru District, Arusha Region**, 2017.
3. Siphael Betuel, **Development of a VPN-based Approach for Improving
Access to and Sharing of Patient's Records across Health Facilities in Tanzania**, 2017.
4. Wambura Wambura, **Development of Discharge Letter Module onto Care2X Hospital Information System**, 2017.
